#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBJava16
    image: postgres
    environment:
      POSTGRES_DB: "${PostgreDb}"
      POSTGRES_USER: "${PostgreUser}"
      POSTGRES_PASSWORD: "${PostgrePas}"
    ports:
      - "5432:5432"
    networks:
      java16-network:
        aliases:
          - java16db
networks:
  java16-network:
    name: 'java16_network'
