#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBJava16
    image: postgres
    environment:
      POSTGRES_DB: "${PostgreDb}"
      POSTGRES_USER: "${PostgreUser}"
      POSTGRES_PASSWORD: "${PostgrePas}"
    ports:
      - "5432:5432"
